function init(self)

end

function final(self)

end

function update(self, dt)
	
end

function fixed_update(self, dt)

end

function on_message(self, message_id, message, sender)
	if message_id == hash('move_background') then
		local p = go.get_position()
		p.x = p.x + 0.2 * message.direction
		go.set_position(p)
	end
end

function on_input(self, action_id, action)

end

function on_reload(self)

end
